### ISSUE TITLE
cls-hooked による実行コンテキストの保存と利用

### ISSUE THREAD

**Issue by karszawa** [nestjs-jp/nestjs-meetup-community-conference-2023-cfp#4]
### Twitter ID (必須)

karszawa

### 発表見込み時間 (必須)

15

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

Node.js には Async hooks という非同期処理のライフサイクルイベントをトリガーに任意の処理を実行できるという仕組みがあります。cls-hooked は Async hooks を使いやすく改善したライブラリです。dinii 社では cls-hooked を利用して実行コンテキスト（＝ネットワークリクエストのコンテキスト）を保存・利用するという実装を行っています。

この発表では Async hooks や cls-hooked の分かりやすい説明から、dinii 社での実践的な活用方法をご紹介します。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

プログラミング, アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by kumewata** [comment]
@karszawa 

こんばんは！NestJS meetup 運営です。
この度はご多忙の中、[NestJS MeetUp nestjs-jp/nestjs-meetup-community-conference-2022-cfp#5](https://nest-jp.connpass.com/event/265684/)への登壇申し込みありがとうございます！

- 当日までのコミュニケーションについて
コミュニケーションについてはこちらののIssuesで対応させていただきます！

- イベントページ・当日進行スライドに掲載する企業ロゴ・アイコンについて
当イベントでは登壇者様の所属企業様・ご自身の技術広報の一環として以下の取り組みを行なっています。ご希望の場合は上記コミュニケーション時にお伝えください。
  - 企業ロゴ画像の進行スライドへの掲載(Youtube上で公開されます)
  - ご自身のアイコン画像のイベントページ・進行スライドへの掲載
掲載イメージは過去のイベントをご覧ください
https://www.youtube.com/channel/UChXmcut8xDOG7Rfn5GpHsWg/streams
https://nest-jp.connpass.com/event/255459/

- 当日のリハーサルについて
円滑な進行・疑問点の解消を目的としイベントの19時からリハーサルをさせていただいています。もしご都合が難しい場合は調整させていただきます。

**Comment by naokihaba** [comment]
@karszawa 
お世話になっております！
ご応募いただきました#5 2022/12/23回の登壇者を募集しているのですが、本日時点でまだ応募がない状態です。
来週まで待ってみて+1名あれば開催できればと考えていますが、状況変わらずであれば延期を検討しております。

確定致しましたらご連絡させていただきますが、取り急ぎご連絡いたしました。

**Comment by naokihaba** [comment]
@karszawa
お世話になっております！
登壇枠が規定2名に満たなかったため、今月会についてはスキップとさせていただきます🙇
またのご参加をお待ちしております

**Comment by karszawa** [comment]
承知しました！またよろしくおねがいします！

**Comment by naokihaba** [comment]
🙇

**Comment by naokihaba** [comment]
@karszawa 

お疲れ様です！
前回中止となりました#5を3月31日に開催いたします。
ご都合宜しければ是非ご登壇いただきたくご連絡させていただきました

https://nest-jp.connpass.com/event/276469/

**Comment by karszawa** [comment]
@NaokiHaba ご案内ありがとうございます！登壇者として参加登録させていただきました！発表内容等はこちらのものと同様でお願いします 🙇

**Comment by naokihaba** [comment]
@karszawa 
ありがとうございます！
ではこちらの内容を2023年のレポジトリに移動いたします🙇

**Comment by naokihaba** [comment]
@karszawa 

当日の発表順についてのご希望ございますでしょうか？？

2番〜ラストまで現在空いている状態です

**Comment by karszawa** [comment]
@NaokiHaba では2番でお願いします！

**Comment by naokihaba** [comment]
@karszawa 
かしこまりました！
それでは2番目で確定させていただきます

**Comment by ikkyu-3** [comment]
@karszawa
運営の長谷川です。この度は、イベントへのご参加ありがとうございます。

只今、運営側で使用するスライドの準備をしております。

[運営側で使用するスライド](https://www.canva.com/design/DAFdmT6LEgk/DoK6lAKEU2EXFn8QySMunw/view?utm_content=DAFdmT6LEgk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

スライドでアイコンを使用したいのですが、ご希望ありますでしょうか？
あればアイコンを共有していただけると幸いです🙏
特にない場合は、アイコンを使用しない表示に変更する予定です。

また、お手数なのですがスライドに不備(会社ロゴ等)がないかご確認お願い致します。
何かありましたら、こちらにコメントいただけると幸いです。

**Comment by karszawa** [comment]
@ikkyu-3 こちらでお願いします！

![profile](https://user-images.githubusercontent.com/1257695/227453885-6061e06b-e86f-48b0-b63d-dfb527c56f31.jpg)

会社ロゴ問題ありません 🙆‍♂️

**Comment by naokihaba** [comment]
@karszawa 
ありがとうございます！
反映いたしました。

**Comment by ikkyu-3** [comment]
@karszawa 
共有ありがとうございます🙏
