### ISSUE TITLE
NestJS への API リプレース体験記（仮）

### ISSUE THREAD

**Issue by choco14t** [nestjs-jp/nestjs-meetup-community-conference-2023-cfp#5]
### Twitter ID (必須)

choco14t

### 発表見込み時間 (必須)

15 - 20分

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

Rails + Apollo Federation で実装された API を NestJS に移行している際に取り組んだこと、直面した課題について話そうと思います。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

プログラミング, アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by NaokiHaba** [comment]
### 連絡事項

この度は、イベントへのご参加ありがとうございます。

当日までは、こちらでやりとりをさせていただければと思います。

早速ですが、イベントの配信スライドで利用するアイコンや所属企業名の公開はご希望でしょうか？

イメージとしては、[こちら](https://nest-jp.connpass.com/event/255459/)になります

**Comment by naokihaba** [comment]
@choco14t 

連絡事項
この度は、イベントへのご参加ありがとうございます。

当日までは、こちらでやりとりをさせていただければと思います。

早速ですが、イベントの配信スライドで利用するアイコンや所属企業名の公開はご希望でしょうか？

イメージとしては、[こちら](https://nest-jp.connpass.com/event/255459/)になります

**Comment by choco14t** [comment]
@NaokiHaba 
返信が遅くなりました 🙇🏻 
下記でお願いできますでしょうか？

- 所属 [株式会社スペースマーケット](https://spacemarket.co.jp/)
- アイコン https://pbs.twimg.com/profile_images/1504709357740883968/XVYzzOEj_400x400.jpg

**Comment by naokihaba** [comment]
@choco14t 
ありがとうございます！
イベントページに掲載させていただきました

https://nest-jp.connpass.com/event/276469/

**Comment by naokihaba** [comment]
@choco14t 

当日の発表順についてのご希望ございますでしょうか？？

2番〜ラストまで現在空いている状態です

**Comment by choco14t** [comment]
@NaokiHaba 3番目を希望します！

**Comment by naokihaba** [comment]
@choco14t 
ありがとうございます！
では3番目で確定いたします

**Comment by ikkyu-3** [comment]
@choco14t 
運営の長谷川です。この度は、イベントへのご参加ありがとうございます。

只今、運営側で使用するスライドの準備をしております。

[運営側で使用するスライド](https://www.canva.com/design/DAFdmT6LEgk/DoK6lAKEU2EXFn8QySMunw/view?utm_content=DAFdmT6LEgk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

お手数なのですが、スライドに不備(会社ロゴ等)がないかご確認お願い致します。
何かありましたら、こちらにコメントいただけると幸いです。

**Comment by choco14t** [comment]
@ikkyu-3 
確認が遅くなりました。
10枚目のスライドですが、 `choco14t氏` となっているところを `choco氏` に編集お願いできますでしょうか？ 🙇🏻

**Comment by naokihaba** [comment]
@choco14t 
こちら訂正させていただきました🙇
