### ISSUE TITLE
NestJsにおける例外処理とロギングの仕方

### ISSUE THREAD

**Issue by ampersand-github** [nestjs-jp/nestjs-meetup-community-conference-2023-cfp#6]
### Twitter ID (必須)

@ampersand000

### 発表見込み時間 (必須)

20

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

NestJsには、例外を処理するための強力な機能が搭載されています。
例外フィルター機能を使うことで、アプリケーションで発生した例外をフィルタリングすることができます。

また、NestJsはロギング機能も提供しています。
この機能を使うことで、イベントやエラーを記録することができます。

例外フィルターとロギング機能を組み合わせることで、アプリケーションのバグやエラーを迅速に特定し、修正することができます。

今回はこの2つの機能をNestJS上でどう実装するのか説明します。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
@ampersand-github 

連絡事項
この度は、イベントへのご参加ありがとうございます。

当日までは、こちらでやりとりをさせていただければと思います。

早速ですが、イベントの配信スライドで利用するアイコンや所属企業名の公開はご希望でしょうか？

イメージとしては、[こちら](https://nest-jp.connpass.com/event/255459/)になります

**Comment by naokihaba** [comment]
@ampersand-github  

当日の発表順についてのご希望ございますでしょうか？？
特にご希望なければ空いている枠でお願いする形になります

**Comment by ikkyu-3** [comment]
@ampersand-github 
運営の長谷川です。この度は、イベントへのご参加ありがとうございます。

只今、運営側で使用するスライドの準備をしております。

[運営側で使用するスライド](https://www.canva.com/design/DAFdmT6LEgk/DoK6lAKEU2EXFn8QySMunw/view?utm_content=DAFdmT6LEgk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

スライドでアイコンを使用したいのですが、ご希望ありますでしょうか？
あればアイコンを共有していただけると幸いです🙏
特にない場合は、~~アイコンを使用しない~~ Twitter で使用されているアイコンに変更する予定です。

また、お手数なのですがスライドに不備がないかご確認お願い致します。
何かありましたら、こちらにコメントいただけると幸いです。

**Comment by naokihaba** [comment]
@ampersand-github 

当日19時からリハーサルをさせていただきます。

時間になりましたら、こちらに入室をお願いします

 https://streamyard.com/fgj4ecqtwy

**Comment by ampersand-github** [comment]
@NaokiHaba 
申し訳ありません。
今気づきました。

>当日19時からリハーサルをさせていただきます。

承知しました、当日はよろしくお願いします

**Comment by naokihaba** [comment]
@ampersand-github 
ご確認ありがとうございます！
当日はよろしくお願いいたします🙇
